spring.application.name=deputados-back-end
#user=postgres pss=admin
spring.datasource.url=jdbc:postgresql://localhost:5432/deputados-aplicacao-banco
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


jwt.secret=uma_chave_super_secreta_bem_grande_123456789
jwt.access-expiration-minutes=15
jwt.refresh-expiration-days=30